HTTP Health Checker in workflow
alpaylan/afetbilgi.com pull request #82
Opened 2023-02-10 00:17 UTC by cagriefegunay

Edited `cron-data-upload.yaml` for checking the availability with valid HTTP codes before running other jobs

2023-02-10 00:23 UTC, oznakn requested changes
we need another cron workflow file for the healtcheck, and we also need a healthcheck for the file https://cdn.afetbilgi.com/latest.json

2023-02-10 05:28 UTC, oznakn commented
cdn url yi koymak lazım

5dk ya düşürelim cron u

2023-02-11 22:38 UTC, ozansz approved these changes
nice! thans for collaboration

2023-02-11 22:38 UTC, ozansz commented on .github/workflows/cron-data-upload.yaml
> +    - cron: "*/6 * * * *" # Run every 30 minutes
```suggestion
    - cron: "*/30 * * * *" # Run every 30 minutes
```

2023-02-11 22:38 UTC, ozansz commented on .github/workflows/http-health-check.yaml
> +          sites: '["https://afetbilgi.com", "https://www.afetbilgi.com", "https://maps.afetbilgi.com", "https://cdn.afetbilgi.com/latest.json", "https://pdf.afetbilgi.com"]'
```suggestion
          sites: '["https://afetbilgi.com", "https://www.afetbilgi.com", "https://maps.afetbilgi.com", "https://cdn.afetbilgi.com/latest.json","https://cdn.afetbilgi.com/schema.json", "https://pdf.afetbilgi.com", "https://pdf.afetbilgi.com/index.json"]'
```

2023-02-11 22:40 UTC, merged